### ISSUE TITLE
Looking forward to open source

### ISSUE THREAD

**Issue by KeoChi** [touristCheng/UCSNet#1]
Hello. I have been reading your paper "[Deep Stereo using Adaptive Thin Volume Representation with Uncertainty Awareness](https://arxiv.org/pdf/1911.12012.pdf)". Thank you for your contribution．And expecting the code to be available soon. Thank you.

**Comment by whubaichuan** [comment]
@KeoChi hi, the [paper](https://paperswithcode.com/paper/cascade-cost-volume-for-high-resolution-multi) may be useful for you.
