### ISSUE TITLE
point cloud visualization in the paper

### ISSUE THREAD

**Issue by kwea123** [touristCheng/UCSNet#2]
Why is the point cloud in Figure 5. look so clean? Especially on the bottom left, the word "POTHEKE" on the billboard looks so clear. I have tested many other MVS algorithms but none of them looks that clear.

Even with ground truth, it looks totally different from what you have in the paper...
![gt](https://user-images.githubusercontent.com/11364490/75784108-0ac6a900-5da5-11ea-907e-bedccbb22877.png)
I wonder if it's the visualization software that makes difference. I use python open3d to visualize. What visualizer are you using?

**Comment by kwea123** [comment]
OK I realized. Maybe it's point size? I reduced the point size and now it looks better.

**Comment by Kammagod** [comment]
> OK I realized. Maybe it's point size? I reduced the point size and now it looks better.

hi, how do you reduce the point size?
